/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaniniShopeCheckoutRouteImport } from './routes/panini-shope-checkout'
import { Route as PaniniCheckoutRouteImport } from './routes/panini-checkout'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BrindeRouteImport } from './routes/brinde'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressRouteImport } from './routes/address'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaniniShopeIndexRouteImport } from './routes/panini-shope.index'
import { Route as PaniniCopaIndexRouteImport } from './routes/panini-copa.index'
import { Route as UpsellTaxaEnvioRouteImport } from './routes/upsell.taxa-envio'
import { Route as PaniniShopeSlugRouteImport } from './routes/panini-shope.$slug'
import { Route as PaniniCopaSlugRouteImport } from './routes/panini-copa.$slug'
import { Route as ApiPublicTestUtmifyRouteImport } from './routes/api/public/test-utmify'
import { Route as ApiPublicReconcileSalesRouteImport } from './routes/api/public/reconcile-sales'
import { Route as ApiPublicKlivopayWebhookRouteImport } from './routes/api/public/klivopay-webhook'
import { Route as ApiPublicIronpayWebhookRouteImport } from './routes/api/public/ironpay-webhook'
import { Route as ApiPublicFreepayWebhookRouteImport } from './routes/api/public/freepay-webhook'

const PaniniShopeCheckoutRoute = PaniniShopeCheckoutRouteImport.update({
  id: '/panini-shope-checkout',
  path: '/panini-shope-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniCheckoutRoute = PaniniCheckoutRouteImport.update({
  id: '/panini-checkout',
  path: '/panini-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindeRoute = BrindeRouteImport.update({
  id: '/brinde',
  path: '/brinde',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniShopeIndexRoute = PaniniShopeIndexRouteImport.update({
  id: '/panini-shope/',
  path: '/panini-shope/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniCopaIndexRoute = PaniniCopaIndexRouteImport.update({
  id: '/panini-copa/',
  path: '/panini-copa/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellTaxaEnvioRoute = UpsellTaxaEnvioRouteImport.update({
  id: '/upsell/taxa-envio',
  path: '/upsell/taxa-envio',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniShopeSlugRoute = PaniniShopeSlugRouteImport.update({
  id: '/panini-shope/$slug',
  path: '/panini-shope/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniCopaSlugRoute = PaniniCopaSlugRouteImport.update({
  id: '/panini-copa/$slug',
  path: '/panini-copa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestUtmifyRoute = ApiPublicTestUtmifyRouteImport.update({
  id: '/api/public/test-utmify',
  path: '/api/public/test-utmify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconcileSalesRoute = ApiPublicReconcileSalesRouteImport.update({
  id: '/api/public/reconcile-sales',
  path: '/api/public/reconcile-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKlivopayWebhookRoute =
  ApiPublicKlivopayWebhookRouteImport.update({
    id: '/api/public/klivopay-webhook',
    path: '/api/public/klivopay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIronpayWebhookRoute = ApiPublicIronpayWebhookRouteImport.update({
  id: '/api/public/ironpay-webhook',
  path: '/api/public/ironpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFreepayWebhookRoute = ApiPublicFreepayWebhookRouteImport.update({
  id: '/api/public/freepay-webhook',
  path: '/api/public/freepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRoute
  '/brinde': typeof BrindeRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/panini-checkout': typeof PaniniCheckoutRoute
  '/panini-shope-checkout': typeof PaniniShopeCheckoutRoute
  '/panini-copa/$slug': typeof PaniniCopaSlugRoute
  '/panini-shope/$slug': typeof PaniniShopeSlugRoute
  '/upsell/taxa-envio': typeof UpsellTaxaEnvioRoute
  '/panini-copa/': typeof PaniniCopaIndexRoute
  '/panini-shope/': typeof PaniniShopeIndexRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/ironpay-webhook': typeof ApiPublicIronpayWebhookRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
  '/api/public/reconcile-sales': typeof ApiPublicReconcileSalesRoute
  '/api/public/test-utmify': typeof ApiPublicTestUtmifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRoute
  '/brinde': typeof BrindeRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/panini-checkout': typeof PaniniCheckoutRoute
  '/panini-shope-checkout': typeof PaniniShopeCheckoutRoute
  '/panini-copa/$slug': typeof PaniniCopaSlugRoute
  '/panini-shope/$slug': typeof PaniniShopeSlugRoute
  '/upsell/taxa-envio': typeof UpsellTaxaEnvioRoute
  '/panini-copa': typeof PaniniCopaIndexRoute
  '/panini-shope': typeof PaniniShopeIndexRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/ironpay-webhook': typeof ApiPublicIronpayWebhookRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
  '/api/public/reconcile-sales': typeof ApiPublicReconcileSalesRoute
  '/api/public/test-utmify': typeof ApiPublicTestUtmifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRoute
  '/brinde': typeof BrindeRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/panini-checkout': typeof PaniniCheckoutRoute
  '/panini-shope-checkout': typeof PaniniShopeCheckoutRoute
  '/panini-copa/$slug': typeof PaniniCopaSlugRoute
  '/panini-shope/$slug': typeof PaniniShopeSlugRoute
  '/upsell/taxa-envio': typeof UpsellTaxaEnvioRoute
  '/panini-copa/': typeof PaniniCopaIndexRoute
  '/panini-shope/': typeof PaniniShopeIndexRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/ironpay-webhook': typeof ApiPublicIronpayWebhookRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
  '/api/public/reconcile-sales': typeof ApiPublicReconcileSalesRoute
  '/api/public/test-utmify': typeof ApiPublicTestUtmifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address'
    | '/admin'
    | '/brinde'
    | '/checkout'
    | '/pagamento'
    | '/panini-checkout'
    | '/panini-shope-checkout'
    | '/panini-copa/$slug'
    | '/panini-shope/$slug'
    | '/upsell/taxa-envio'
    | '/panini-copa/'
    | '/panini-shope/'
    | '/api/public/freepay-webhook'
    | '/api/public/ironpay-webhook'
    | '/api/public/klivopay-webhook'
    | '/api/public/reconcile-sales'
    | '/api/public/test-utmify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address'
    | '/admin'
    | '/brinde'
    | '/checkout'
    | '/pagamento'
    | '/panini-checkout'
    | '/panini-shope-checkout'
    | '/panini-copa/$slug'
    | '/panini-shope/$slug'
    | '/upsell/taxa-envio'
    | '/panini-copa'
    | '/panini-shope'
    | '/api/public/freepay-webhook'
    | '/api/public/ironpay-webhook'
    | '/api/public/klivopay-webhook'
    | '/api/public/reconcile-sales'
    | '/api/public/test-utmify'
  id:
    | '__root__'
    | '/'
    | '/address'
    | '/admin'
    | '/brinde'
    | '/checkout'
    | '/pagamento'
    | '/panini-checkout'
    | '/panini-shope-checkout'
    | '/panini-copa/$slug'
    | '/panini-shope/$slug'
    | '/upsell/taxa-envio'
    | '/panini-copa/'
    | '/panini-shope/'
    | '/api/public/freepay-webhook'
    | '/api/public/ironpay-webhook'
    | '/api/public/klivopay-webhook'
    | '/api/public/reconcile-sales'
    | '/api/public/test-utmify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  AdminRoute: typeof AdminRoute
  BrindeRoute: typeof BrindeRoute
  CheckoutRoute: typeof CheckoutRoute
  PagamentoRoute: typeof PagamentoRoute
  PaniniCheckoutRoute: typeof PaniniCheckoutRoute
  PaniniShopeCheckoutRoute: typeof PaniniShopeCheckoutRoute
  PaniniCopaSlugRoute: typeof PaniniCopaSlugRoute
  PaniniShopeSlugRoute: typeof PaniniShopeSlugRoute
  UpsellTaxaEnvioRoute: typeof UpsellTaxaEnvioRoute
  PaniniCopaIndexRoute: typeof PaniniCopaIndexRoute
  PaniniShopeIndexRoute: typeof PaniniShopeIndexRoute
  ApiPublicFreepayWebhookRoute: typeof ApiPublicFreepayWebhookRoute
  ApiPublicIronpayWebhookRoute: typeof ApiPublicIronpayWebhookRoute
  ApiPublicKlivopayWebhookRoute: typeof ApiPublicKlivopayWebhookRoute
  ApiPublicReconcileSalesRoute: typeof ApiPublicReconcileSalesRoute
  ApiPublicTestUtmifyRoute: typeof ApiPublicTestUtmifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panini-shope-checkout': {
      id: '/panini-shope-checkout'
      path: '/panini-shope-checkout'
      fullPath: '/panini-shope-checkout'
      preLoaderRoute: typeof PaniniShopeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-checkout': {
      id: '/panini-checkout'
      path: '/panini-checkout'
      fullPath: '/panini-checkout'
      preLoaderRoute: typeof PaniniCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brinde': {
      id: '/brinde'
      path: '/brinde'
      fullPath: '/brinde'
      preLoaderRoute: typeof BrindeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-shope/': {
      id: '/panini-shope/'
      path: '/panini-shope'
      fullPath: '/panini-shope/'
      preLoaderRoute: typeof PaniniShopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-copa/': {
      id: '/panini-copa/'
      path: '/panini-copa'
      fullPath: '/panini-copa/'
      preLoaderRoute: typeof PaniniCopaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell/taxa-envio': {
      id: '/upsell/taxa-envio'
      path: '/upsell/taxa-envio'
      fullPath: '/upsell/taxa-envio'
      preLoaderRoute: typeof UpsellTaxaEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-shope/$slug': {
      id: '/panini-shope/$slug'
      path: '/panini-shope/$slug'
      fullPath: '/panini-shope/$slug'
      preLoaderRoute: typeof PaniniShopeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-copa/$slug': {
      id: '/panini-copa/$slug'
      path: '/panini-copa/$slug'
      fullPath: '/panini-copa/$slug'
      preLoaderRoute: typeof PaniniCopaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-utmify': {
      id: '/api/public/test-utmify'
      path: '/api/public/test-utmify'
      fullPath: '/api/public/test-utmify'
      preLoaderRoute: typeof ApiPublicTestUtmifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconcile-sales': {
      id: '/api/public/reconcile-sales'
      path: '/api/public/reconcile-sales'
      fullPath: '/api/public/reconcile-sales'
      preLoaderRoute: typeof ApiPublicReconcileSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/klivopay-webhook': {
      id: '/api/public/klivopay-webhook'
      path: '/api/public/klivopay-webhook'
      fullPath: '/api/public/klivopay-webhook'
      preLoaderRoute: typeof ApiPublicKlivopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ironpay-webhook': {
      id: '/api/public/ironpay-webhook'
      path: '/api/public/ironpay-webhook'
      fullPath: '/api/public/ironpay-webhook'
      preLoaderRoute: typeof ApiPublicIronpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freepay-webhook': {
      id: '/api/public/freepay-webhook'
      path: '/api/public/freepay-webhook'
      fullPath: '/api/public/freepay-webhook'
      preLoaderRoute: typeof ApiPublicFreepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  AdminRoute: AdminRoute,
  BrindeRoute: BrindeRoute,
  CheckoutRoute: CheckoutRoute,
  PagamentoRoute: PagamentoRoute,
  PaniniCheckoutRoute: PaniniCheckoutRoute,
  PaniniShopeCheckoutRoute: PaniniShopeCheckoutRoute,
  PaniniCopaSlugRoute: PaniniCopaSlugRoute,
  PaniniShopeSlugRoute: PaniniShopeSlugRoute,
  UpsellTaxaEnvioRoute: UpsellTaxaEnvioRoute,
  PaniniCopaIndexRoute: PaniniCopaIndexRoute,
  PaniniShopeIndexRoute: PaniniShopeIndexRoute,
  ApiPublicFreepayWebhookRoute: ApiPublicFreepayWebhookRoute,
  ApiPublicIronpayWebhookRoute: ApiPublicIronpayWebhookRoute,
  ApiPublicKlivopayWebhookRoute: ApiPublicKlivopayWebhookRoute,
  ApiPublicReconcileSalesRoute: ApiPublicReconcileSalesRoute,
  ApiPublicTestUtmifyRoute: ApiPublicTestUtmifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
