/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BrindeRouteImport } from './routes/brinde'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressRouteImport } from './routes/address'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaniniCopaIndexRouteImport } from './routes/panini-copa.index'
import { Route as PaniniCopaSlugRouteImport } from './routes/panini-copa.$slug'
import { Route as ApiPublicKlivopayWebhookRouteImport } from './routes/api/public/klivopay-webhook'
import { Route as ApiPublicFreepayWebhookRouteImport } from './routes/api/public/freepay-webhook'

const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindeRoute = BrindeRouteImport.update({
  id: '/brinde',
  path: '/brinde',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniCopaIndexRoute = PaniniCopaIndexRouteImport.update({
  id: '/panini-copa/',
  path: '/panini-copa/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaniniCopaSlugRoute = PaniniCopaSlugRouteImport.update({
  id: '/panini-copa/$slug',
  path: '/panini-copa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKlivopayWebhookRoute =
  ApiPublicKlivopayWebhookRouteImport.update({
    id: '/api/public/klivopay-webhook',
    path: '/api/public/klivopay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFreepayWebhookRoute = ApiPublicFreepayWebhookRouteImport.update({
  id: '/api/public/freepay-webhook',
  path: '/api/public/freepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRoute
  '/brinde': typeof BrindeRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/panini-copa/$slug': typeof PaniniCopaSlugRoute
  '/panini-copa/': typeof PaniniCopaIndexRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRoute
  '/brinde': typeof BrindeRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/panini-copa/$slug': typeof PaniniCopaSlugRoute
  '/panini-copa': typeof PaniniCopaIndexRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/admin': typeof AdminRoute
  '/brinde': typeof BrindeRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/panini-copa/$slug': typeof PaniniCopaSlugRoute
  '/panini-copa/': typeof PaniniCopaIndexRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
  '/api/public/klivopay-webhook': typeof ApiPublicKlivopayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address'
    | '/admin'
    | '/brinde'
    | '/checkout'
    | '/pagamento'
    | '/panini-copa/$slug'
    | '/panini-copa/'
    | '/api/public/freepay-webhook'
    | '/api/public/klivopay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address'
    | '/admin'
    | '/brinde'
    | '/checkout'
    | '/pagamento'
    | '/panini-copa/$slug'
    | '/panini-copa'
    | '/api/public/freepay-webhook'
    | '/api/public/klivopay-webhook'
  id:
    | '__root__'
    | '/'
    | '/address'
    | '/admin'
    | '/brinde'
    | '/checkout'
    | '/pagamento'
    | '/panini-copa/$slug'
    | '/panini-copa/'
    | '/api/public/freepay-webhook'
    | '/api/public/klivopay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  AdminRoute: typeof AdminRoute
  BrindeRoute: typeof BrindeRoute
  CheckoutRoute: typeof CheckoutRoute
  PagamentoRoute: typeof PagamentoRoute
  PaniniCopaSlugRoute: typeof PaniniCopaSlugRoute
  PaniniCopaIndexRoute: typeof PaniniCopaIndexRoute
  ApiPublicFreepayWebhookRoute: typeof ApiPublicFreepayWebhookRoute
  ApiPublicKlivopayWebhookRoute: typeof ApiPublicKlivopayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brinde': {
      id: '/brinde'
      path: '/brinde'
      fullPath: '/brinde'
      preLoaderRoute: typeof BrindeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-copa/': {
      id: '/panini-copa/'
      path: '/panini-copa'
      fullPath: '/panini-copa/'
      preLoaderRoute: typeof PaniniCopaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panini-copa/$slug': {
      id: '/panini-copa/$slug'
      path: '/panini-copa/$slug'
      fullPath: '/panini-copa/$slug'
      preLoaderRoute: typeof PaniniCopaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/klivopay-webhook': {
      id: '/api/public/klivopay-webhook'
      path: '/api/public/klivopay-webhook'
      fullPath: '/api/public/klivopay-webhook'
      preLoaderRoute: typeof ApiPublicKlivopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freepay-webhook': {
      id: '/api/public/freepay-webhook'
      path: '/api/public/freepay-webhook'
      fullPath: '/api/public/freepay-webhook'
      preLoaderRoute: typeof ApiPublicFreepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  AdminRoute: AdminRoute,
  BrindeRoute: BrindeRoute,
  CheckoutRoute: CheckoutRoute,
  PagamentoRoute: PagamentoRoute,
  PaniniCopaSlugRoute: PaniniCopaSlugRoute,
  PaniniCopaIndexRoute: PaniniCopaIndexRoute,
  ApiPublicFreepayWebhookRoute: ApiPublicFreepayWebhookRoute,
  ApiPublicKlivopayWebhookRoute: ApiPublicKlivopayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
